(() => {"use strict";
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const key="drift-design-workshop-v1";let saved={};try{saved=JSON.parse(localStorage.getItem(key)||"{}") }catch(_){saved={}};
  function persist(){localStorage.setItem(key,JSON.stringify(saved))}
  const mode=$("#workshop-mode");if(saved.workshop){document.body.classList.add("workshop-hidden");mode?.setAttribute("aria-pressed","true")}
  mode?.addEventListener("click",()=>{const on=document.body.classList.toggle("workshop-hidden");mode.setAttribute("aria-pressed",String(on));saved.workshop=on;persist()});
  $("#reset-all")?.addEventListener("click",()=>{if(confirm("Reset workshop progress and all interactive settings?")){localStorage.removeItem(key);location.reload()}});
  const progress=$("#reading-progress");function updateProgress(){const max=document.documentElement.scrollHeight-innerHeight,p=max?scrollY/max:0;progress.style.width=`${Math.min(100,p*100)}%`;saved[document.body.dataset.page||"page"]=Math.round(p*100);persist()}addEventListener("scroll",updateProgress,{passive:true});updateProgress();
  // Build a cell-ID-backed chapter table of contents.
  const toc=$(".toc"), links=$(".toc-links");if(toc&&links){$$(`.notebook-lesson h2,.notebook-lesson h3`).forEach((h,i)=>{if(!h.id){const cell=h.closest("[data-cell-id]");h.id=(cell?`heading-${cell.dataset.cellId}`:`heading-${i}`)}const a=document.createElement("a");a.href=`#${h.id}`;a.textContent=h.textContent;a.dataset.level=h.tagName.slice(1);links.append(a)});$(".toc-toggle")?.addEventListener("click",()=>toc.classList.toggle("open"));const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){$$('.toc a').forEach(a=>a.classList.toggle('active',a.hash===`#${e.target.id}`))}}),{rootMargin:"-20% 0px -70%"});$$(`.notebook-lesson h2,.notebook-lesson h3`).forEach(h=>obs.observe(h))}
  $$(".copy-code").forEach(b=>b.addEventListener("click",async()=>{const code=b.closest(".code-panel").querySelector("code").textContent;await navigator.clipboard.writeText(code);const old=b.textContent;b.textContent="Copied";setTimeout(()=>b.textContent=old,1200)}));
  window.Workshop={$, $$, fetchJSON:async path=>{const r=await fetch(path);if(!r.ok)throw new Error(`${path}: ${r.status}`);return r.json()},fetchF32:async path=>{const r=await fetch(path);if(!r.ok)throw new Error(`${path}: ${r.status}`);return new Float32Array(await r.arrayBuffer())},normal:(x,m,s)=>Math.exp(-.5*((x-m)/s)**2)/(s*Math.sqrt(2*Math.PI)),quantile:(values,q)=>{const a=[...values].sort((x,y)=>x-y),p=(a.length-1)*q,i=Math.floor(p),d=p-i;return a[i]+(a[Math.min(i+1,a.length-1)]-a[i])*d},softmax:logs=>{const m=Math.max(...logs),v=logs.map(x=>Math.exp(x-m)),s=v.reduce((a,b)=>a+b,0);return v.map(x=>x/s)}};
})();
