(() => {"use strict";const{$}=Workshop,P=WorkshopPlots;
  const c=$("#evo-canvas");if(!c)return;const ids=["mut-wt","mut-loh","wtri","wloh","p0","duration","ne","reps","seed"],el=Object.fromEntries(ids.map(x=>[x,$(`#evo-${x}`)]));let timer=null,visible=12,last=[];
  function rng(seed){let a=(seed>>>0)||1;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
  function normal(R){const u=Math.max(R(),1e-12),v=R();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
  function binomial(n,p,R){if(n<=0||p<=0)return 0;if(p>=1)return n;if(n<=10000){let k=0;for(let i=0;i<n;i++)if(R()<p)k++;return k}const mean=n*p,sd=Math.sqrt(n*p*(1-p));return Math.max(0,Math.min(n,Math.round(mean+sd*normal(R))))}
  function simulate(seed){const R=rng(seed),N=+el.ne.value,steps=+el.duration.value*10,muW=10**(+el["mut-wt"].value),muL=10**(+el["mut-loh"].value),w=[+el.wtri.value,1,+el.wloh.value];let p=[+el.p0.value,(1-+el.p0.value)*.75,(1-+el.p0.value)*.25],out=[p.slice()];for(let g=1;g<=steps;g++){const mut=[p[0]*(1-muW-muL),p[1]+p[0]*muW,p[2]+p[0]*muL],sel=mut.map((x,i)=>x*w[i]),z=sel.reduce((a,b)=>a+b,0),q=sel.map(x=>x/z);const n0=binomial(N,q[0],R),n1=binomial(N-n0,q[1]/Math.max(1-q[0],1e-12),R);p=[n0/N,n1/N,(N-n0-n1)/N];if(g%10===0)out.push(p.slice())}return out}
  function draw(){const reps=Math.max(1,Math.min(24,+el.reps.value||1));last=Array.from({length:reps},(_,i)=>simulate((+el.seed.value||0)+i));const dur=+el.duration.value,show=Math.min(visible,dur),f=P.frame(c,0,1,0,dur),xs=Array.from({length:dur+1},(_,i)=>i),cols=[P.C.tri,P.C.wt,P.C.loh];last.forEach((traj,r)=>cols.forEach((color,s)=>P.line(f,xs.slice(0,show+1),traj.slice(0,show+1).map(x=>x[s]),color,r===0?2:.9,r===0?.9:.17)));["Aneuploid","Wild type","LOH"].forEach((name,i)=>P.text(f,name,dur*.72,.96-i*.07,{color:cols[i],font:"bold 12px system-ui"}));const final=last.map(x=>x[show]);const med=[0,1,2].map(s=>Workshop.quantile(final.map(x=>x[s]),.5));$("#evo-composition").innerHTML=["Aneuploid","Wild type","LOH"].map((n,i)=>`<span><b>${n}</b><br>${(med[i]*100).toFixed(1)}% median</span>`).join("");const selection=Math.abs(1-+el.wtri.value)+Math.abs(1-+el.wloh.value),conversion=10**(+el["mut-wt"].value)+10**(+el["mut-loh"].value),drift=1/Math.sqrt(+el.ne.value);const driver=selection>conversion*40&&selection>drift*4?"selection":conversion>drift*.3?"conversion / mutation":"stochastic variation";$("#evo-driver").textContent=`The visible pattern is mainly driven by ${driver} under this setting.`;$("#evo-summary").textContent=`${reps} seeded replicate${reps>1?'s':''}; showing passage ${show}. Median final composition: ${(med[0]*100).toFixed(1)}% aneuploid, ${(med[1]*100).toFixed(1)}% wild type, ${(med[2]*100).toFixed(1)}% LOH. For Nₑ > 10,000 the browser uses a seeded normal approximation to binomial drift.`}
  function labels(){$("#evo-mut-wt-label").textContent=`10^${(+el["mut-wt"].value).toFixed(2)} / generation`;$("#evo-mut-loh-label").textContent=`10^${(+el["mut-loh"].value).toFixed(2)} / generation`;$("#evo-wtri-label").textContent=(+el.wtri.value).toFixed(3);$("#evo-wloh-label").textContent=(+el.wloh.value).toFixed(3);$("#evo-p0-label").textContent=`${(+el.p0.value*100).toFixed(0)}%`;$("#evo-duration-label").textContent=`${el.duration.value} passages`;visible=+el.duration.value;draw()}
  let debounce;Object.values(el).forEach(e=>e.addEventListener("input",()=>{clearTimeout(debounce);debounce=setTimeout(labels,70)}));
  const presets={balanced:[-4,-4.4,.96,.99,.99,12,100000,8],selection:[-5.5,-5.5,.9,1.03,.99,12,100000,8],conversion:[-2.8,-3.2,.99,1,.99,12,100000,8],drift:[-5,-5,.99,1.01,.95,12,1000,16]};document.querySelectorAll("[data-evo-preset]").forEach(b=>b.addEventListener("click",()=>{const v=presets[b.dataset.evoPreset];[el["mut-wt"],el["mut-loh"],el.wtri,el.wloh,el.p0,el.duration,el.ne,el.reps].forEach((x,i)=>x.value=v[i]);labels()}));
  $("#evo-play").addEventListener("click",e=>{if(timer){clearInterval(timer);timer=null;e.target.textContent="Play";return}visible=0;e.target.textContent="Pause";timer=setInterval(()=>{visible++;draw();if(visible>=+el.duration.value){clearInterval(timer);timer=null;e.target.textContent="Play"}},350)});$("#evo-controls").addEventListener("reset",()=>setTimeout(labels));addEventListener("resize",draw);labels();
})();
