(() => {"use strict";
  const C={ink:"#21312c",muted:"#607069",grid:"#d8d2c5",tri:"#315f52",wt:"#577d91",loh:"#b56a50",clay:"#b56a50",gold:"#c59b4f",orange:"#e67e22",purple:"#8e44ad",blue:"#577d91",paper:"#fffdf8"};
  function frame(canvas, yMin=0, yMax=1, xMin=0, xMax=1){const ratio=window.devicePixelRatio||1,w=canvas.clientWidth||+canvas.getAttribute("width"),aspect=(+canvas.getAttribute("height"))/(+canvas.getAttribute("width")),h=Math.max(240,w*aspect);canvas.style.height=`${h}px`;canvas.width=Math.round(w*ratio);canvas.height=Math.round(h*ratio);const ctx=canvas.getContext("2d");ctx.setTransform(ratio,0,0,ratio,0,0);const p={l:48,r:18,t:38,b:38};ctx.clearRect(0,0,w,h);ctx.fillStyle=C.paper;ctx.fillRect(0,0,w,h);const X=x=>p.l+(x-xMin)/Math.max(xMax-xMin,1e-9)*(w-p.l-p.r),Y=y=>h-p.b-(y-yMin)/Math.max(yMax-yMin,1e-9)*(h-p.t-p.b);ctx.strokeStyle=C.grid;ctx.fillStyle=C.muted;ctx.font="11px system-ui";ctx.lineWidth=1;for(let i=0;i<=4;i++){const y=yMin+(yMax-yMin)*i/4;ctx.beginPath();ctx.moveTo(p.l,Y(y));ctx.lineTo(w-p.r,Y(y));ctx.stroke();ctx.fillText(y.toFixed(Math.abs(yMax-yMin)<1?2:1),5,Y(y)+4)}ctx.beginPath();ctx.moveTo(p.l,p.t);ctx.lineTo(p.l,h-p.b);ctx.lineTo(w-p.r,h-p.b);ctx.strokeStyle=C.ink;ctx.stroke();return{ctx,w,h,p,X,Y};}
  function line(f,xs,ys,color,width=2,alpha=1,dash=[]){const{ctx,X,Y}=f;ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.globalAlpha=alpha;ctx.setLineDash(dash);ctx.beginPath();ys.forEach((y,i)=>{const x=X(xs[i]);i?ctx.lineTo(x,Y(y)):ctx.moveTo(x,Y(y))});ctx.stroke();ctx.restore();}
  function points(f,xs,ys,color,r=4,open=false){const{ctx,X,Y}=f;xs.forEach((x,i)=>{ctx.beginPath();ctx.arc(X(x),Y(ys[i]),r,0,Math.PI*2);ctx.fillStyle=open?C.paper:color;ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke()})}
  function band(f,xs,lo,hi,color,alpha=.15){const{ctx,X,Y}=f;ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle=color;ctx.beginPath();xs.forEach((x,i)=>i?ctx.lineTo(X(x),Y(lo[i])):ctx.moveTo(X(x),Y(lo[i])));for(let i=xs.length-1;i>=0;i--)ctx.lineTo(X(xs[i]),Y(hi[i]));ctx.closePath();ctx.fill();ctx.restore()}
  function text(f,value,x,y,opts={}){const{ctx,X,Y}=f;ctx.save();ctx.fillStyle=opts.color||C.ink;ctx.font=opts.font||"12px system-ui";ctx.textAlign=opts.align||"left";ctx.fillText(value,X(x),Y(y));ctx.restore()}
  function legend(f,items){const{ctx,p,w}=f;ctx.save();ctx.font="bold 10px system-ui";ctx.textBaseline="middle";let x=p.l,y=13;items.forEach((item,index)=>{const label=typeof item==="string"?item:item.label,color=typeof item==="string"?C.ink:item.color||C.ink,needed=ctx.measureText(label).width+30;if(index&&x+needed>w-p.r){x=p.l;y=28}ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+14,y);ctx.stroke();ctx.fillText(label,x+19,y);x+=needed});ctx.restore()}
  window.WorkshopPlots={C,frame,line,points,band,text,legend};
})();
